name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: psf/black@stable

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .
      - name: Lint with flake8
        run: flake8
      - name: Mypy
        run: mypy
      - name: Run tests with Coverage
        run: |
          coverage run -m unittest discover
          coverage report -m
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          flags: unittests
